# Generated by Django 4.0.3 on 2022-05-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.PositiveIntegerField(choices=[(1, 'admin'), (2, 'technetium'), (3, 'operator')], default=2),
            preserve_default=False,
        ),
    ]
