# Generated by Django 4.0.3 on 2022-05-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_resetpasswordcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetpasswordcode',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resetpasswordcode',
            name='code',
            field=models.CharField(default=None, max_length=7, null=True, unique=True),
        ),
    ]
