# Generated by Django 4.0.3 on 2022-04-26 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(max_length=255)),
                ('ar_name', models.CharField(max_length=255)),
                ('parent_cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lookups.productcat')),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(max_length=255)),
                ('ar_name', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='toppings/')),
                ('product_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookups.productcat')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='drinks/')),
                ('en_name', models.CharField(max_length=255)),
                ('ar_name', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('is_topping', models.BooleanField()),
                ('product_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookups.productcat')),
            ],
        ),
    ]
