# Generated by Django 4.0.3 on 2022-05-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0002_remove_topping_product_cat_product_toppings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='drinks/')),
                ('tag', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='is_image',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
