# Generated by Django 4.0.3 on 2022-05-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0002_remove_topping_product_cat_product_toppings'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_order',
            name='topping',
        ),
        migrations.AddField(
            model_name='product_order',
            name='topping',
            field=models.ManyToManyField(blank=True, null=True, to='lookups.topping'),
        ),
    ]
