# Generated by Django 4.0.3 on 2022-05-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_product_order_topping_product_order_topping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='qr_code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
